language: ruby
rvm:
  - 2.0.0
before_script: 
  - psql -c 'create database my_workout_diary_test;' -U postgres
  - bundle exec rake db:migrate
script: bundle exec rspec spec
env: 
  - MWD_MAIL_USERNAME="fake_user_email@fake_mail.test" MWD_HOSTNAME="fake_hostname.com"
notifications:
  email: false