setup: &SETUP
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode


development:
  <<: *SETUP
  host: localhost
  database: my_workout_diary_development
  min_messages: notice

test:
  <<: *SETUP
  host: localhost
  database: my_workout_diary_test
  min_messages: notice

# Heroku doesn't use this
# production:
#   <<: *SETUP
#   database: my_workout_diary_production